[package]
name = "cw-ics721-bridge"
version = "0.1.0"
authors = ["Zeke Medley <zekemedley@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
cosmwasm-storage = "1.0.0"
cw-storage-plus = "0.13.4"
cw-utils = "0.13.4"
cw2 = "0.13.4"
cw721 = "0.13.4"
cw721-base = { version = "0.13.4", features = [] } # TODO: add library back in when: https://github.com/CosmWasm/cw-nfts/pull/76
schemars = "0.8.10"
serde = { version = "1.0.140", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
ics721-escrow = { version = "0.1.0", path = "../ics721-escrow", features = ["library"] }
cw-paginate = { git = "https://github.com/DA0-DA0/dao-contracts.git" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
cw-multi-test = "0.13.4"
# cw721-base = { version = "0.13.4" }
ics721-escrow = { path = "../ics721-escrow", version = "*" }