[package]
name = "ics721"
version = "0.1.0"
edition = "2021"
authors = ["ekez <ekez@withoutdoing.com>", "mr-t <mr-t@arkprotocol.io>", "Art3mix <art3mix.90@gmail.com>", "m@publicawesome.com", "s+git@publicawesome.com"]
description = "an implementation of the ICS721 specification for transfering NFTs between blockchains"

[dependencies]
bech32 = { workspace = true }
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
cw-ownable      = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true, features = ["library"] }
cw721-base-016  = { workspace = true, features = ["library"] }
ics721-types = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
cw-paginate-storage = { workspace = true }
cw721-incoming-proxy = { workspace = true }
cw721-outgoing-proxy-derive = { workspace = true }
cw-pause-once = { workspace = true }
cw-cii = { workspace = true }
sha2 = { workspace = true }
zip-optional = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
cw2 = { workspace = true }
cw721-016 = { workspace = true }
cw721-outgoing-proxy-rate-limit = { workspace = true }
